"""Adding chat table

Revision ID: 6ed2de4c2a5b
Revises: 0bda1a537774
Create Date: 2025-07-11 15:43:59.504776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed2de4c2a5b'
down_revision: Union[str, Sequence[str], None] = '0bda1a537774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_from', sa.Integer(), nullable=True),
    sa.Column('msg_content', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('msg_reply', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['msg_from'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_chats')
    # ### end Alembic commands ###
